apiVersion: v1
kind: Service
metadata:
  name: authservice
  namespace: p3
spec:
  selector:
    app: auth-service
    version: green  # Initially pointing to blue
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30002
  type: NodePort