apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice-blue
  namespace: p3
  labels:
    app: auth-service
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
      version: blue
  template:
    metadata:
      labels:
        app: auth-service
        version: blue
    spec:
      containers:
      - name: auth-container
        image: nithingganesh/authimg:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
