apiVersion: v1
kind: Service
metadata:
  name: orderservice
  namespace: p3
spec:
  selector:
    app: order-service
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30003
  type: NodePort
