apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice-blue
  namespace: p3
  labels:
    app: order-service
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
      version: blue
  template:
    metadata:
      labels:
        app: order-service
        version: blue
    spec:
      containers:
      - name: order-container
        image: nithingganesh/orderimg:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
