apiVersion: v1
kind: Service
metadata:
  name: productservice
  namespace: p3
spec:
  selector:
    app: product-service
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30004
  type: NodePort
