apiVersion: apps/v1
kind: Deployment
metadata:
  name: productservice
  namespace: p3
  labels:
    app: product-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-container
        image: nithingganesh/productimg:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
