apiVersion: apps/v1
kind: Deployment
metadata:
  name: productservice-green
  namespace: p3
  labels:
    app: product-service
    version: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
      version: green
  template:
    metadata:
      labels:
        app: product-service
        version: green
    spec:
      containers:
      - name: product-container
        image: nithingganesh/productimg:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
